
[uv.kernel]
name = "Sparkrl+uv"
pyspark_name = "Sparkrl+uv (Pyspark)"

[http_config]
proxy = "http://localhost:8090"
verify = false

[livy_client]
url = "http://livy.localhost:8998"
page_size = 20
max_results = 1001
log_batch_size = 100
poll_pause = 2.0
default_headers = { "Content-Type" = "application/json" }

[livy_client.auth]
# type = "kerberos"

[retry_policy]
type = "custom-interval"
retry_seconds_to_sleep_list = [0.2, 0.5, 1.0, 3.0, 5.0]
configurable_retry_policy_max_retries = 8

[delete_policy]
type = "max-time"
time = 15.0
pause = 1.5

[readiness_policy]
type = "max-time"
time = 60.0
pause = 2.0

[session_configs]
name = "livy-uploads-dev-session"
driverMemory = "1000M"
executorCores = 1
executorMemory = "1000M"
heartbeatTimeoutInSecond = 600
ttl = "10m"

[sparkmagic]
conf_dir = "${SPARKMAGIC_CONF_DIR:-.dev/conf/sparkmagic}"
".include" = [".dev/conf/sparkmagic/config.yaml"]

[sparkmagic.session_configs]
".include" = ["#/session_configs"]
