import io
import itertools
import json
from pathlib import Path
from typing import Mapping, Optional, Tuple

from dotenv import dotenv_values, find_dotenv

MARKER = "# AUTO-GENERATED BY "
NAME = "livy-uploads"


def envfile_load(
    filename: Optional[str] = None,
    interpolate: bool = True,
) -> Tuple[Optional[Path], Mapping[str, str]]:
    """
    Loads a configuration from an environment file found in the directory hierarchy, starting
    from the current working directory.

    Args:
        filename: The name of the environment file to load.
        interpolate: Whether to interpolate variable references `${...}`.

    Returns:
        A tuple containing the env file path and the loaded values.
    """
    filename = filename or ".env"

    if found_path := find_dotenv(filename):
        env_path = Path(found_path).absolute()
        text = env_path.read_text()
    elif found_path := find_dotenv(f"{filename}.example"):
        env_path = Path(found_path).absolute().with_name(filename)
        text = Path(found_path).read_text()
    else:
        return None, {}

    text = _get_before_marker(text)
    raw_values = dotenv_values(stream=io.StringIO(text), interpolate=interpolate)
    values = {k: v for k, v in raw_values.items() if v is not None}

    return env_path, values


def envfile_save(
    path: Path,
    values: Mapping[str, str],
    quote: bool = False,
    name: Optional[str] = None,
) -> None:
    """
    Saves values to an environment file.

    Args:
        path: The path to the environment file.
        values: The values to save.
        quote: Whether to quote the values.
        name: The name to use in the auto-generated marker. Defaults to the module-global :attr:`NAME`.
    """
    path = path.absolute()
    marker = MARKER + (name or NAME)

    try:
        text = path.read_text()
    except FileNotFoundError:
        text = ""

    text = _get_before_marker(text).strip() + f"\n\n\n{marker}\n\n"

    for k, v in values.items():
        if quote:
            v = json.dumps(v, ensure_ascii=False)
        text += f"{k}={v}\n"

    tmp_path = path.with_suffix(".save.tmp")
    path.parent.mkdir(parents=True, exist_ok=True)

    with tmp_path.open("w") as fp:
        fp.write(text)

    tmp_path.replace(path)


def _get_before_marker(text: str) -> str:
    lines = text.splitlines()
    return "\n".join(itertools.takewhile(lambda line: not line.startswith(MARKER), lines))
