# mypy: disable-error-code=no-untyped-def
from collections.abc import Mapping
from pathlib import Path

import pytest

from livy_uploads.configs.envfile import envfile_load, envfile_save


class TestLoadEnvfileConfig:
    @pytest.fixture
    def sample_env_content(self) -> str:
        return """
# This is a comment
FOO=bar
BAZ=qux
EMPTY_VALUE=
"""

    @pytest.fixture
    def sample_env_with_marker(self) -> str:
        return """
# User defined values
FOO=bar
BAZ=qux

# AUTO-GENERATED BY livy-uploads
AUTO_KEY=auto_value
ANOTHER_AUTO=another_value
"""

    @pytest.fixture
    def sample_env_with_interpolation(self) -> str:
        return """
BASE_PATH=/home/user
PROJECT_PATH=${BASE_PATH}/project
"""

    def test_envfile_load_file_not_found(self, tmp_path: Path, monkeypatch):
        # setup
        monkeypatch.setattr("livy_uploads.configs.envfile.find_dotenv", lambda x: "")

        # act
        result_path, result_values = envfile_load()

        # verify
        assert result_path is None
        assert result_values == {}

    def test_envfile_load_loads_basic_values(self, tmp_path: Path, sample_env_content: str, monkeypatch):
        # setup
        env_file = tmp_path / ".env"
        env_file.write_text(sample_env_content)
        monkeypatch.setattr("livy_uploads.configs.envfile.find_dotenv", lambda x: str(env_file))

        # act
        result_path, result_values = envfile_load()

        # verify
        assert result_path == tmp_path
        assert "FOO" in result_values
        assert result_values["FOO"] == "bar"
        assert "BAZ" in result_values
        assert result_values["BAZ"] == "qux"

    def test_envfile_load_filters_empty_values(self, tmp_path: Path, sample_env_content: str, monkeypatch):
        # setup
        env_file = tmp_path / ".env"
        env_file.write_text(sample_env_content)
        monkeypatch.setattr("livy_uploads.configs.envfile.find_dotenv", lambda x: str(env_file))

        # act
        result_path, result_values = envfile_load()

        # verify
        # Note: dotenv_values returns empty string for EMPTY_VALUE=, not None
        # The function only filters None values, so empty strings remain
        assert "EMPTY_VALUE" in result_values
        assert result_values["EMPTY_VALUE"] == ""

    def test_envfile_load_ignores_auto_generated_section(
        self, tmp_path: Path, sample_env_with_marker: str, monkeypatch
    ):
        # setup
        env_file = tmp_path / ".env"
        env_file.write_text(sample_env_with_marker)
        monkeypatch.setattr("livy_uploads.configs.envfile.find_dotenv", lambda x: str(env_file))

        # act
        result_path, result_values = envfile_load()

        # verify
        assert "FOO" in result_values
        assert "BAZ" in result_values
        assert "AUTO_KEY" not in result_values
        assert "ANOTHER_AUTO" not in result_values

    def test_envfile_load_with_interpolation_enabled(
        self, tmp_path: Path, sample_env_with_interpolation: str, monkeypatch
    ):
        # setup
        env_file = tmp_path / ".env"
        env_file.write_text(sample_env_with_interpolation)
        monkeypatch.setattr("livy_uploads.configs.envfile.find_dotenv", lambda x: str(env_file))

        # act
        result_path, result_values = envfile_load(interpolate=True)

        # verify
        assert result_values["BASE_PATH"] == "/home/user"
        assert result_values["PROJECT_PATH"] == "/home/user/project"

    def test_envfile_load_with_interpolation_disabled(
        self, tmp_path: Path, sample_env_with_interpolation: str, monkeypatch
    ):
        # setup
        env_file = tmp_path / ".env"
        env_file.write_text(sample_env_with_interpolation)
        monkeypatch.setattr("livy_uploads.configs.envfile.find_dotenv", lambda x: str(env_file))

        # act
        result_path, result_values = envfile_load(interpolate=False)

        # verify
        assert result_values["BASE_PATH"] == "/home/user"
        assert result_values["PROJECT_PATH"] == "${BASE_PATH}/project"

    def test_envfile_load_custom_filename(self, tmp_path: Path, monkeypatch):
        # setup
        env_file = tmp_path / ".env.custom"
        env_file.write_text("CUSTOM_KEY=custom_value\n")
        monkeypatch.setattr("livy_uploads.configs.envfile.find_dotenv", lambda x: str(env_file))

        # act
        result_path, result_values = envfile_load(filename=".env.custom")

        # verify
        assert result_path == tmp_path
        assert result_values["CUSTOM_KEY"] == "custom_value"


class TestSaveEnvfileValues:
    @pytest.fixture
    def sample_values(self) -> Mapping[str, str]:
        return {"KEY1": "value1", "KEY2": "value2"}

    @pytest.fixture
    def existing_env_content(self) -> str:
        return """# User defined values
USER_KEY=user_value
ANOTHER_KEY=another_value
"""

    @pytest.fixture
    def existing_env_with_marker(self) -> str:
        return """# User defined values
USER_KEY=user_value

# AUTO-GENERATED BY livy-uploads
OLD_AUTO=old_value
"""

    def test_envfile_save_creates_new_file(self, tmp_path: Path, sample_values: Mapping[str, str]):
        # setup
        env_file = tmp_path / ".env"

        # act
        envfile_save(env_file, sample_values)

        # verify
        assert env_file.exists()
        content = env_file.read_text()
        assert "KEY1=value1" in content
        assert "KEY2=value2" in content
        assert "# AUTO-GENERATED BY" in content

    def test_envfile_save_appends_to_existing_file(
        self, tmp_path: Path, existing_env_content: str, sample_values: Mapping[str, str]
    ):
        # setup
        env_file = tmp_path / ".env"
        env_file.write_text(existing_env_content)

        # act
        envfile_save(env_file, sample_values)

        # verify
        content = env_file.read_text()
        assert "USER_KEY=user_value" in content
        assert "ANOTHER_KEY=another_value" in content
        assert "KEY1=value1" in content
        assert "KEY2=value2" in content

    def test_envfile_save_replaces_auto_generated_section(
        self,
        tmp_path: Path,
        existing_env_with_marker: str,
        sample_values: Mapping[str, str],
    ):
        # setup
        env_file = tmp_path / ".env"
        env_file.write_text(existing_env_with_marker)

        # act
        envfile_save(env_file, sample_values)

        # verify
        content = env_file.read_text()
        assert "USER_KEY=user_value" in content
        assert "OLD_AUTO=old_value" not in content
        assert "KEY1=value1" in content
        assert "KEY2=value2" in content

    def test_envfile_save_with_quote_enabled(self, tmp_path: Path, sample_values: Mapping[str, str]):
        # setup
        env_file = tmp_path / ".env"
        values_with_special = {"KEY1": "value with spaces", "KEY2": "value\nwith\nnewlines"}

        # act
        envfile_save(env_file, values_with_special, quote=True)

        # verify
        content = env_file.read_text()
        assert 'KEY1="value with spaces"' in content
        assert 'KEY2="value\\nwith\\nnewlines"' in content

    def test_envfile_save_with_custom_name(self, tmp_path: Path, sample_values: Mapping[str, str]):
        # setup
        env_file = tmp_path / ".env"

        # act
        envfile_save(env_file, sample_values, name="custom-app")

        # verify
        content = env_file.read_text()
        assert "# AUTO-GENERATED BY" in content

    def test_envfile_save_creates_parent_directories(self, tmp_path: Path, sample_values: Mapping[str, str]):
        # setup
        env_file = tmp_path / "subdir" / "nested" / ".env"

        # act
        envfile_save(env_file, sample_values)

        # verify
        assert env_file.exists()
        assert env_file.parent.exists()
        content = env_file.read_text()
        assert "KEY1=value1" in content

    def test_envfile_save_uses_atomic_write(self, tmp_path: Path, sample_values: Mapping[str, str]):
        # setup
        env_file = tmp_path / ".env"
        env_file.write_text("ORIGINAL=content\n")

        # act
        envfile_save(env_file, sample_values)

        # verify
        tmp_file = env_file.with_suffix(".save.tmp")
        assert not tmp_file.exists()
        assert env_file.exists()
        content = env_file.read_text()
        assert "KEY1=value1" in content
